name: baby_care_app
description: A simple baby care tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  path_provider: ^2.1.1
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Share/Export
  share_plus: ^7.2.1
  
  # Date/Time
  intl: ^0.18.1
  
  # UI
  cupertino_icons: ^1.0.2
  
  # Animations (optional)
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    # Icons for UI elements
    - assets/icons/
    - assets/icons/bottle.png
    - assets/icons/droplet.png
    - assets/icons/poop.png
    - assets/icons/clock.png
    - assets/icons/history.png
    - assets/icons/settings.png
    - assets/icons/export.png
    - assets/icons/notification.png
    
    # Images and illustrations
    - assets/images/
    - assets/images/splash/
    - assets/images/illustrations/
    - assets/images/app_icon/
    
    # Animations
    - assets/animations/
    
    # Fonts directory
    - assets/fonts/
  
  # Custom fonts
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300