name: baby_care_app
description: A simple baby care tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.0
  
  # Local Storage
  path_provider: ^2.1.3
  
  # Notifications (compatible with Android Embedding V2)
  flutter_local_notifications: ^19.4.2
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Share/Export
  share_plus: ^12.0.0
  
  # Date/Time
  intl: ^0.20.2
  
  # UI
  cupertino_icons: ^1.0.2
  
  # Animations (optional)
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/splash/
    - assets/images/illustrations/
    - assets/images/app_icon/
    - assets/animations/
    - assets/fonts/
  
  # Custom fonts
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
