name: baby_care_app
description: A simple baby care tracking app for new parents
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management - Fixed version to avoid conflicts
  flutter_riverpod: ^2.4.9
  
  # Local Storage - Compatible versions
  path_provider: ^2.1.1
  
  # Notifications - Fixed to stable version that works with Android Embedding V2
  flutter_local_notifications: ^15.1.3
  
  # Permissions - Stable version
  permission_handler: ^11.0.1
  
  # Share/Export - Fixed version
  share_plus: ^7.2.1
  
  # Date/Time - Stable version
  intl: ^0.18.1
  
  # UI Icons
  cupertino_icons: ^1.0.6
  
  # Optional: Animations
  # lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  
  # For testing
  test: ^1.24.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/splash/
    - assets/images/illustrations/
    - assets/images/app_icon/
    - assets/animations/
    - assets/fonts/
  
  # Custom fonts
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
