name: Build and Deploy Baby Care App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  FLUTTER_VERSION: '3.35.4'
  JAVA_VERSION: '17'

jobs:
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: ${{ env.FLUTTER_VERSION }}
  #         cache: false

  #     - name: Check Flutter version
  #       run: flutter --version

  #     - name: Flutter Doctor
  #       run: flutter doctor -v

  #     - name: Get dependencies
  #       run: flutter pub get

  #     - name: Analyze project
  #       run: flutter analyze --fatal-infos

  #     - name: Run tests (if present)
  #       run: |
  #         if [ -d "test" ] && [ "$(find test -name '*.dart' | wc -l)" -gt 0 ]; then
  #           flutter test --coverage
  #         else
  #           echo "No tests present"
  #         fi

  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Set up Android SDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Check Flutter & Android setup
        run: |
          flutter doctor -v
          echo "ANDROID_HOME=$ANDROID_HOME"
          ls -la $ANDROID_HOME

      - name: Ensure Gradle wrapper is executable
        run: chmod +x android/gradlew

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release -v

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: baby-care-apk-${{ github.sha }}
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 30

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: false

      - name: Check Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href "/baby-care-app/" -v

      - name: Upload web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build-${{ github.sha }}
          path: build/web/
          retention-days: 30
